#!/usr/bin/env bash

directory=$(find ~ ~/Documents ~/Documents/Code ~/Documents/Configuration -mindepth 1 -maxdepth 1 -type d | fzf)
window_name=$(basename "$directory" | tr . _)

tmux new-window -n "$window_name" -c "$directory"

tmux switch-client -t "$window_name"

